name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  test:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2
        with:
          repository: Duckynet-com/java_assignment
          path: main-repo

      - name: Checkout Test Repository
        uses: actions/checkout@v2
        with:
          repository: Duckynet-com/java_assignment_test
          path: test-repo

      - name: List directories for debugging
        run: |
          ls -l
          echo "Listing main-repo:"
          ls -l main-repo
          echo "Listing test-repo:"
          ls -l test-repo

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd main-repo/src
          javac App.java

      - name: Download JUnit
        run: |
          mkdir lib
          curl -L -o lib/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.1/junit-platform-console-standalone-1.7.1.jar

      - name: Compile and Run Tests
        run: |
          cd test-repo/test
          javac -cp .:../../main-repo/src:../../lib/junit-platform-console-standalone.jar AppTest.java
          java -jar ../../lib/junit-platform-console-standalone.jar --class-path .:../../main-repo/src --scan-classpath
