name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  test:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2
        with:
          repository: Duckynet-com/java_assignment
          path: main-repo

      - name: Checkout Test Repository
        uses: actions/checkout@v2
        with:
          repository: Duckynet-com/java_assignment_test
          path: test-repo

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd main-repo/src
          javac App.java

      - name: Run Test
        run: |
          cd ../../test-repo/test
          javac -cp .:../../main-repo/src HelloWorldTest.java
          java -cp .:../../main-repo/src org.junit.runner.JUnitCore HelloWorldTest
